### PR TITLE
Trac 1138

### PR DESCRIPTION
**Pull request by ghost**
** TRAC-1138**: https://jira.lib.utk.edu/browse/TRAC-1138

**_https://github.com/utkdigitalinitiatives/TRACE/pull/51_** will need to be completed before this Pull Request can be successfully merged .

# What does this Pull Request do?

The pull request makes changes to two files. One file is modified to change the name of a function. 
The name of the function is trace_ext_workflow_add_or_update_policy_datastream . This new function
replaces 2 functions, one of which was not being used.

The new replacement function will check to see if an object needs a POLICY datastream and creates if one
is not available. if a POLICY datastream is available then the POLICY will only be updated if the POLICIES
are different.

The new function ensures that the correct POLICY is set during ingestions.

# What's new?
The new replacement function will check to see if an object needs a POLICY datastream and creates if one
is not available. If a POLICY datastream is available then the POLICY will only be updated if the POLICIES
are different.

# How should this be tested?

Testing should be performed by uploading a thesis or dissertation to TRACE and ensuring that a policy  is 
set on the object. The state of the object and the policy should be obversed after the object has been 
accepted and published.

1.  Alter the file TRACE/scripts/modules.sh
		a. change line 54 to read git clone -b TRAC-1138 https://github.com/utkdigitalinitiatives/trace_ext_workflow.git 

2.  Update the TRACE vm via your preferred method:

		a. I like vagrant destroy /vagrant up
		
3.  Login as Admin and update the following rules. Goto admininal top nav bar's drop down window for Configuration > Workflow > Rules. 

Click on the button import rule. For each entry below, cut and paste the rule, between the dashed lines,  into the form. Click 'Overwrite' and click 'Import' button.

```
----------------------------------------------------------------------------------------------

{ "islandora_batch_report_email_report" : {
    "LABEL" : "Email: islandora_batch_report_email_report",
    "PLUGIN" : "reaction rule",
    "OWNER" : "rules",
    "REQUIRES" : [ "rules", "islandora_batch_report" ],
    "ON" : { "islandora_batch_report_prepare_daily_report" : [] },
    "DO" : [
      { "mail" : {
          "to" : "vagrant+report@localhost.com",
          "subject" : "Daily Islandora Batch Ingest Report - [report-date-timestamp:value:custom:m\/d\/Y]",
          "message" : "On [report-date-timestamp:value:custom:M jS], [successful-object-total:value] objects were ingested:\r\n[content-model-successful-ingest-breakdown:value]\r\n[successful-set-total:value] sets were successfully processed.\r\n[failed-set-total:value] sets failed processing.\r\n\r\nThere are still:\r\n[ready-to-process-sets:value] sets that remain to be processed.\r\n[ready-to-process-objects:value] objects that remain to be processed.",
          "language" : "en"
        }
      }
    ]
  }
}

----------------------------------------------------------------------------------------------

{ "islandora_book_batch_notify_admin" : {
    "LABEL" : "Email: E-mail admin",
    "PLUGIN" : "reaction rule",
    "OWNER" : "rules",
    "REQUIRES" : [ "islandora", "rules", "islandora_book_batch" ],
    "ON" : { "islandora_book_batch_ingested" : [] },
    "IF" : [
      { "islandora_object_has_relationship" : {
          "subject" : [ "book-object" ],
          "pred_uri" : "http:\/\/islandora.ca\/ontology\/relsext#",
          "pred" : "email-admin-when-ingested",
          "object" : "true",
          "type" : 1
        }
      }
    ],
    "DO" : [
      { "mail" : {
          "to" : "vagrant+admin-role@localhost.com",
          "subject" : "[[site:name]] \u0022[book-object:label]\u0022 has been ingested",
          "message" : "[book-object:label] has been ingested as [book-object:id].\r\n\r\nFor Debugging: E-mail admin Book ingestion",
          "language" : [ "" ]
        }
      },
      { "islandora_object_remove_relationship" : {
          "subject" : [ "book-object" ],
          "pred_uri" : "http:\/\/islandora.ca\/ontology\/relsext#",
          "pred" : "email-admin-when-ingested",
          "object" : "true",
          "type" : 1
        }
      }
    ]
  }
}

----------------------------------------------------------------------------------------------

{ "islandora_scholar_embargo_object_lift_expired_embargo" : {
    "PLUGIN" : "reaction rule",
    "OWNER" : "rules",
    "REQUIRES" : [ "islandora_scholar_embargo" ],
    "ON" : { "islandora_scholar_object_embargo_expired" : [] },
    "DO" : [ { "islandora_scholar_embargo_lift_embargo" : [] } ]
  }
}

----------------------------------------------------------------------------------------------

{ "islandora_scholar_embargo_datastreams_lift_expired_embargo" : {
    "LABEL" : "islandora_scholar_embargo_datastreams_lift_expired_embargo",
    "PLUGIN" : "reaction rule",
    "OWNER" : "rules",
    "REQUIRES" : [ "islandora_scholar_embargo" ],
    "ON" : { "islandora_scholar_datastreams_embargo_expired" : [] },
    "DO" : [
      { "islandora_scholar_embargo_lift_embargo" : { "object" : [ "object" ], "datastream" : [ "datastreams" ] } }
    ]
  }
}

----------------------------------------------------------------------------------------------

{ "rules_addauthuserrole" : {
    "LABEL" : "addauthuserrole",
    "PLUGIN" : "reaction rule",
    "OWNER" : "rules",
    "REQUIRES" : [ "rules" ],
    "ON" : { "user_insert" : [] },
    "DO" : [
      { "user_add_role" : { "account" : [ "account" ], "roles" : { "value" : { "4" : "4" } } } }
    ]
  }
}

----------------------------------------------------------------------------------------------

{ "rules_new_datastream_was_added" : {
    "LABEL" : "Email: New Datastream was added",
    "PLUGIN" : "reaction rule",
    "OWNER" : "rules",
    "REQUIRES" : [ "rules", "islandora" ],
    "ON" : { "islandora_datastream_ingested" : [] },
    "IF" : [
      { "text_matches" : { "text" : [ "datastream:id" ], "match" : "PDF" } },
      { "AND" : [
          { "text_matches" : {
              "text" : [ "object:id" ],
              "match" : "utk.ir.td",
              "operation" : "starts"
            }
          }
        ]
      }
    ],
    "DO" : [
      { "mail_to_users_of_role" : {
          "roles" : { "value" : { "6" : "6" } },
          "subject" : "[[site:name]] \u0022[object:label]\u0022 has a new datastream",
          "message" : "[object:label] by [object:owner] has been ingested as [object:id].\r\nDate created: [object:createdDate]\r\nSubmission: [site:url]\/islandora\/object\/[object:id]\r\n\r\nDatastream [datastream:label]\r\nAdded : [datastream:id]\r\n\r\nDebugging: New Datastream was added Rule",
          "from" : "vagrant@localhost"
        }
      }
    ]
  }
}

----------------------------------------------------------------------------------------------

{ "rules_updated_metadata_form_notification" : {
    "LABEL" : "Email: Updated Metadata Form Notification",
    "PLUGIN" : "reaction rule",
    "OWNER" : "rules",
    "REQUIRES" : [ "rules", "islandora" ],
    "ON" : { "islandora_datastream_modified" : [] },
    "IF" : [
      { "text_matches" : { "text" : [ "datastream:id" ], "match" : "MODS" } }
    ],
    "DO" : [
      { "mail_to_users_of_role" : {
          "roles" : { "value" : { "6" : "6" } },
          "subject" : "[[site:name]] \u0022[object:label]\u0022 has been modified",
          "message" : "[object:label] by [object:owner] has been modified as [object:id].\r\nModified: [datastream:id]\r\nDate created: [object:createdDate]\r\nModified on: [site:current-date]\r\n\r\nSubmission: [site:url]\/islandora\/object\/[object:id]\r\n\r\nThe form was used to modify the information associated with the submission. ",
          "from" : "vagrant@localhost"
        }
      }
    ]
  }
}

----------------------------------------------------------------------------------------------

{ "rules_trace_publishing_workflow_email_notification" : {
    "LABEL" : "Email: Trace Publishing Workflow Email Notification",
    "PLUGIN" : "reaction rule",
    "WEIGHT" : "10",
    "OWNER" : "rules",
    "REQUIRES" : [ "rules", "islandora" ],
    "ON" : { "islandora_object_ingested" : [] },
    "IF" : [
      { "NOT text_matches" : { "text" : [ "object:owner" ], "match" : "bdysonsm" } },
      { "NOT text_matches" : { "text" : [ "object:owner" ], "match" : "comyn7" } },
      { "NOT text_matches" : { "text" : [ "object:owner" ], "match" : "mbagget1" } },
      { "AND" : [
          { "text_matches" : {
              "text" : [ "object:id" ],
              "match" : "utk.ir.td",
              "operation" : "starts"
            }
          }
        ]
      },
      { "NOT text_matches" : { "text" : [ "object:owner" ], "match" : "rwaltz" } }
    ],
    "DO" : [
      { "mail_to_users_of_role" : {
          "roles" : { "value" : { "6" : "6" } },
          "subject" : "[[site:name]] \u0022[object:label]\u0022 has been ingested",
          "message" : "[object:label] by [object:owner] has been ingested as [object:id].\r\nDate created: [object:createdDate]\r\nSubmission: [site:url]\/islandora\/object\/[object:id]\r\n\r\nFor Debugging: Trace Publishing Workflow",
          "from" : "vagrant@localhost"
        }
      },
      { "mail" : {
          "to" : "vagrant+[object:owner]@localhost.com",
          "subject" : "TRACE Submission",
          "message" : "Hello [object:owner],\r\n[object:label] [object:createdDate]\r\nPlease go to https:\/\/trace.utk.edu\/user for updates. ",
          "from" : "vagrant@localhost",
          "language" : [ "" ]
        }
      }
    ]
  }
}

----------------------------------------------------------------------------------------------

{ "rules_trace_publishing_workflow_for_nontd" : {
    "LABEL" : "Trace Publishing Workflow for Non TD Submissions",
    "PLUGIN" : "reaction rule",
    "OWNER" : "rules",
    "REQUIRES" : [ "rules", "trace_ext_workflow", "islandora" ],
    "ON" : { "islandora_object_ingested" : [] },
    "IF" : [
      { "NOT text_matches" : {
          "text" : [ "object:id" ],
          "match" : "utk.ir.td",
          "operation" : "starts"
        }
      }
    ],
    "DO" : [
      { "trace_ext_workflow_rules_object_policy_add" : {
          "USING" : { "object" : [ "object" ] },
          "PROVIDE" : { "datastream" : { "datastream" : "Loaded datastream instance" } }
        }
      }
    ]
  }
}


----------------------------------------------------------------------------------------------
```

4.  Logout of admin.

5.  Open window Sign in as userA

6.  Submit a new thesis as userA.

    a. click on the 'Submit' link on the left navigation bar (LNB)
    b. click on the 'Submit Graduate Thesis or Dissertation' link
    c. Fill out form and submit

	
7.   Open up incognito window (private window) and sign in as thesis_manager

8.   Click on the LNB 'Items to Accept'

    a. Find the title of the object that was just submitted and click on it.

9.   Check the datastreams created

    a. click on the Object Manage File's link

    b. click on the link 'POLICY'

    d. the 'POLICY' datastream's rule element with the id 'permit-owner-submitted' 
	
10.   Switch back to the 'My account' screen.

11.    Click on the 'Items to Accept' Button

    a. check the box next to the object to accept.

    b. click on 'Accepted Selected' button, then 'Confirm'

    c. result should be 'One object accepted.'
	
12.  Click on the 'Items to Publish' link

    a. the title of the object should show at the top as a link

    b. click on the object title link

    c. click on the 'Manage files' link

    d. view the POLICY link, it should have multiple versions

    e. click on the link 'POLICY', the 'POLICY' datastream's rule element should have the id 'permit-owner-accepted'

13.  Click on the 'Items to Publish' link

    a. check the box next to the object to accept.

    b. click on 'Publish Selected' button, then 'Confirm'

    c. result should be 'One object published.'
      
    d. the 'POLICY' datastream's rule element should have the id 'permit-public-published'
    
14.   Return to the home page of thesis_manager and choose Browse Collections on the LNB

15.    Click on 'Graduate Thesis and Dissertations'

16.    Find the object in the list of objects and click on the title

    a. The display of the object should be viewable.

    b. the PDF link should be present and actionable

17.    Log out.

18.    As anonymous user click 'Browse Collections' on the LNB

19.    Click on 'Graduate Thesis and Dissertations'

    a. The display of the object should be viewable.

    b. The metadata record should be displayed to the user

    c. the PDF link should be present and actionable

20.    Return to the UserA Window

    a. The display of the object should be viewable.

    b. the PDF link should be present and actionable

    c. The metadata record should be displayed to the user

21. Log out of all Windows

22. Open up the terminal to the TRACE project running the VM

23.  At the command prompt, ssh into vagrant (i.e. vagrant ssh)

24. check email by typing 'mail'

25. You should have received 3 emails.

26. Logout. You are done.

# Additional Notes:
Any additional information that you think would be helpful when reviewing this PR. None.

# Interested parties
Tag (@ mention) interested parties or, if unsure, @utkdigitalinitiatives/digital-initiatives-developers

### CODE REVIEW

**Comment by ghost** [comment]
This pull request is dependent upon the pull request in the TRACE project

**Comment by DonRichards** [comment]
19 C says that after an ETD is submitted and published the pdf should be hidden from a anonymous user?

**Comment by DonRichards** [comment]
Also final step says 9 messages but 3 does look like like it was directly associated with this update.

```log
vagrant@trace:~$ mail
"/var/mail/vagrant": 9 messages 9 new
>N   1 vagrant+thesis_man Wed Jun 13 11:42  34/1233  Message from the Thesis Manager
 N   2 vagrant+thesis_man Wed Jun 13 11:42  34/1215  Message from the Thesis Manager
 N   3 vagrant+thesis_man Wed Jun 13 11:43  34/1233  Message from the Thesis Manager
 N   4 vagrant+thesis_man Wed Jun 13 11:43  34/1215  Message from the Thesis Manager
 N   5 vagrant+thesis_man Wed Jun 13 11:44  21/1158  Message from the Thesis Manager
 N   6 vagrant+thesis_man Wed Jun 13 11:44  21/1140  Message from the Thesis Manager
 N   7 vagrant@localhost  Wed Jun 13 12:25  23/858   [TRACE] "fdszasdfsdfg" has been ingested
 N   8 vagrant@localhost  Wed Jun 13 12:25  21/708   TRACE Submission
 N   9 vagrant@localhost  Wed Jun 13 12:26  27/970   [TRACE] "fdszasdfsdfg" has a new datastream
```

**Review by DonRichards — COMMENTED** [review]
All instruction yields the expected behavior.

**Review by DonRichards — APPROVED** [review]
Tested and works

**Pull request merged**
