### PR TITLE
TRAC-675

### PR DESCRIPTION
**Pull request by ghost**
**TRAC-675**:  [Jira](https://jira.lib.utk.edu/browse/TRAC-675)

# What does this Pull Request do?

This PR in association with changes to islandora_scholar squashes a bug reported as TRAC-675.

The code changes the manner in which the embargo form applies changes to the POLICY datastream. Originally, the POLICY datastream would be edited using the  xacml_editor. Now, Stylesheets are used to transform the content of the POLICY datastream.

Once this is tested, two PRs may be closed, this on in trace_ext_workflow  and the one for islandora_scholar.

# What's new?

changed
includes/trace_ext_workflow.inc

# How should this be tested?

1. Alter the file TRACE/scripts/modules.sh
  a. change line 42 from > git clone https://github.com/utkdigitalinitiatives/trace_ext_workflow.git to > git clone https://github.com/robert-patrick-waltz/trace_ext_workflow.git

  b. EDIT: change line 42 from utkdigitialinitiatives to robert-patrick-waltz

  c. change line 43 from > git clone git clone https://github.com/utkdigitalinitiatives/islandora_scholar to > git clone https://github.com/robert-patrick-waltz/islandora_scholar

  d. EDIT: change line 43 from utkdigitialinitiatives to robert-patrick-waltz

2. Update the TRACE vm via your preferred method:

  a. I like vagrant destroy /vagrant up

3. Open window Sign in as UserA

4. Create a new thesis as UserA.

	a. click on the 'Submit' link on the left navigation bar (LNB)
	
	b. click on the 'Submit Graduate Thesis or Dissertation' link
	
	c. Fill out form and submit

5. Open up incognito window and sign in as thesis_manager

6. Click on the LNB 'Items to Accept'

	a. Find the title of the object that was just submitted and click on it.

7. Click on the Manage Files tab

8. Click on the Embargo link

9. Toggle the 'Datastream' button. 

	a. Check PDF and FULL_TEXT datastreams.
	
	b. Scroll all the way down the page.

10. Confirm the 'Set the embargo date ' toggle button is active

	a. make certain the date is after the current date

11. Press the Update button

	a. The action should result in a message indicating the datastreams are embargoed

12. Check the datastream created

	a. click on the files link
	
	b. view the POLICY link, it should have 2 versions
	
	c. click on the link 'POLICY'
	
	d. the 'POLICY' datastream should contain a rule with the id 'deny-dsid-mime'
	
	e. the 'POLICY' datastream's rule element with the id 'deny-dsid-mime' should have two resources listed 'PDF' and 'FULL_TEXT'

13. Return to the UserA Window

14. On UserA's home page, click on the item created.

15. Click on 'Manage Files'

	a. click on the edit link under 'Operations' column.
	
	b. change the title and save

16. The object should be viewable by UserA with new Title 

17. Switch back to the thesis_manager screen.

18. Click on the 'Items to Accept' Button

	a. check the box next to the object to accept.

	b. click on 'Accepted Selected' button, then 'Confirm'

	c. result should be 'One object accepted.'

19. Click on the 'Items to Publish' link

	a. the title of the object should show at the top as a link

	b. click on the object title link

 a. click on the 'files' link

	b. view the POLICY link, it should have 4 versions

	c. click on the link 'POLICY'

	d. the 'POLICY' datastream should contain a rule with the id 'deny-dsid-mime'

	e. the 'POLICY' datastream's rule element with the id 'deny-dsid-mime' should have two resources listed 'PDF' and 'FULL_TEXT'

20. Return to the UserA Window, click on the item created.

21. Click on 'Manage Files'

	a. click on the edit link under 'Operations' column.

	b. change the title and save

	c. An error page should show indicating the user is unauthorized for the action

22. Switch back to the thesis_manager screen.

23. Click on the 'Items to Publish' Button

	a. check the box next to the object to accept.
	
	b. click on 'Publish Selected' button, then 'Confirm'
	
	c. result should be 'One object published.'

24. Return to the home page of thesis_manager and choose Browse Collections on the LNB

25. Click on 'Graduate Thesis and Dissertations'

26.  Find the object in the list of objects and click on the title

	a. The display of the object should be viewable.
	
	b. the PDF link should be present and actionable
	
	c. The metadata record should be displayed to the user

27. Click on 'Manage Files'

	a. An error page should show indicating the user is unauthorized for the action (this is incorrect behavior so we may want to create a ticket of it now, or fix it now, or just test it later for MVP and create a ticket for it then).

28. Log out.

29. As anonymous user click 'Browse Collections' on the LNB

30. Click on 'Graduate Thesis and Dissertations'

	a. The display of the object should be viewable.
	
	b. The metadata record should be displayed to the user
	
	c. the PDF link should not be present and actionable

31. Return to the UserA Window

	a. The display of the object should be viewable.
	
	b. the PDF link should be present and actionable
	
	c. The metadata record should be displayed to the user

32. Click on 'Manage Files'

	a. An error page should show indicating the user is unauthorized for the action.

# Additional Notes:

# Interested parties
	
@DonRichards @pc37utn @cdeaneGit @CanOfBees

### CODE REVIEW

**Comment by DonRichards** [comment]
31b: For userA the PDF link is there but cannot reach the file via the link after published but currently embargoed. 

http://localhost:8000/islandora/object/utk.ir.td%3A52/datastream/PDF/download/citation.pdf

**Comment by ghost** [comment]
31b: States that the PDF link should be present and actionable.  The action returns a 500 error, and that is fine. The error is expected and is covered by https://jira.lib.utk.edu/browse/TRAC-639

**Comment by CanOfBees** [comment]
looking at this now

**Comment by CanOfBees** [comment]
I am merging this PR with the following understanding: this PR does *not* fix all of the outstanding issues with the XACML POLICY datastream, rather it gives us a method for programmatically modifying the POLICY datastream as the OBJ moves through the workflow.

**Pull request merged**
