### PR TITLE
Address TRAC-899

### PR DESCRIPTION
**Pull request by DonRichards**
## Check list of new functionality for T.E.W.
[ ] Adds default values to existing submissions
[ ] New submissions get the expected values 
[ ] All behaviors the user does submitting & updating will be reflected on '**Items to Accept**'
[ ]  '**Items to Accept**' list should be sorted by the latest modified
[ ]  '**Items to Accept**' list should shows updated information (title, ETD, time stamp)
[ ] When the submission is deleted it will be deleted from the '**Items to Accept**' list

## To test this on vagrant
Please start fresh
```terminal
$ vagrant destroy -f 
$ vagrant up
```

## Before you start
```diff
- DO NOT PULL THIS PULL REQUEST BEFORE YOU RUN A TEST SUBMISSION FIRST!!
```
Do a **couple** of test submissions first before you pull the PR into vagrant. This will create a table as it is on production. This is important to check the update process is working. 

## From terminal
* Go to the module and pull down the PR as a branch
* run 'drush updatedb' & confirm

## Thesis manager
* check the '**Items to Accept**' list (as thesis_manager)
  * This should have 4 columns: **Object** | **Owner** | **ETD** | **Date Modified**
* check that '**Title**' is correct & changes when the title is updated by the user that submitted it
* check that the '**ETD**' status is _blank_ and the '**Date Modified**' is roughly the time the module was installed. This date is not important at this time right now. When the module was installed it gave a default timestamp.
* Run a couple of test submissions as userA / userB with one as a **thesis** and one as **dissertation**. 
  * take note of which one was a Thesis and which was a Dissertation
* check that the '**ETD**' status is correct and check the '**Date Modified**' is correct
* check that any time a datastream or submission is added, edited, or replaced (by the user) that the '**Date Modified**' column is updated and the list resorts the latest to the top. 
* check that when the title is changed it is reflected in the '**Items to Accept**' > '**title**'

## delete checks
* as '**admin**' delete a submission
* check 'Items to Accept' page to verify is has been removed from the list

### CODE REVIEW

**Comment by ghost** [comment]
Probably not related, but I received the following error upon creation of a single thesis. The error occurs on the  'upload your thesis/dissertation form' after metadata form is initially filled out .

> Warning: XSLTProcessor::transformToDoc(): I/O warning : failed to load external entity "/var/www/drupal/sites/all/modules/islandora_xml_forms/builder/self_transforms/trace-disciplines-list-comp.xml" in xml_form_builder_transform_metadata_datastream() (line 611 of /var/www/drupal/sites/all/modules/islandora_xml_forms/builder/xml_form_builder.module).

**Comment by ghost** [comment]
The error Warning was repeated upon my second attempt.

**Comment by ghost** [comment]
Another unrelated item, but http://localhost:8000/islandora/object/<PID>/datastream/MODS/edit takes a really long time to load the form.  and by long I mean like 10 seconds.

**Comment by robert-patrick-waltz** [comment]
Blew up after updating .

> PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'w.representative_body' in 'field list': SELECT w.pid AS pid, w.label AS label, w.user AS user, w.representative_body AS representative_body, w.modified_date AS modified_date FROM {trace_workflow_pids} w WHERE (w.state = :db_condition_placeholder_0) ORDER BY modified_date DESC; Array ( [:db_condition_placeholder_0] => s ) in trace_ext_workflow_select_submitted_records() (line 12 of /var/www/drupal/sites/all/modules/trace_ext_workflow/includes/trace_ext_workflow_dao.inc).

**Comment by CanOfBees** [comment]
@robert-patrick-waltz re: that error that you're seeing -- it's the result of an errant (but not erroneous) merge. To get rid of it:
1. ssh to your vagrant vm
2. in `/home/vagrant`: `sudo cp utk_isl_xml_forms/post_process_transforms/trace-disciplines-list-comp.xml /var/www/drupal/sites/all/modules/islandora_xml_forms/builder/self_transforms/`
3. reload your submission

**Review by ghost — APPROVED** [review]
OK. It tests for me.

**Review by CanOfBees — APPROVED** [review]
Passes testing instructions. @DonRichards thanks.

**Pull request merged**
